---
title: "SolarLab"
author: "Michael Hunt"
date: "March 6, 2016"
output: html_document
---

$$\delta_\odot = \arcsin \left [ \sin \left ( -23.44^\circ \right ) \cdot \cos \left ( \frac{360^\circ}{365.24} \left (N + 10 \right ) + \frac{360^\circ}{\pi} \cdot 0.0167 \sin \left ( \frac{360^\circ}{365.24} \left ( N - 2 \right ) \right ) \right ) \right ]$$

In radians:

$$\delta_\odot=\arcsin \left [ \sin \left (-0.4091^\circ \right) \cdot \cos \left ( \frac{2\pi}{365.24} \left (N+10 \right ) + 0.0334 \cdot \sin \left ( \frac{2\pi}{365.24} \left (N-2 \right ) \right ) \right ) \right ]$$


```{r}
deltaOdot<-function(t){
    # t is the time in day number 1-365
    #t<-t*365
    asin(sin(-0.4091)*cos((2*pi/365.24)*(t+10)+0.0334*sin((2*pi/365.24)*(t-2))))
}

h0<-function(phi,t){
    acos(tan(phi)*tan(deltaOdot(t)))
    }
    
cosTheta<-function(phi,delta,h){
    # theta is the zenith angle
    sin(phi)*sin(delta)+cos(phi)*cos(delta)*cos(h)
}

solarFlux<-function(S0,phi,t){
    h<-pi*(2*(t-floor(t))-1)
    delta<-deltaOdot(t)
    flux<-S0*cosTheta(phi,delta,h)
    flux<-pmax(flux,rep(0,length(t)))
    flux
}
```


```{r}
phi=(pi/180)*50
t=seq(1,365,length.out=365*288)
plot(t,180*deltaOdot(t)/pi,typ="l",ylab="delta")
h0s<-h0(phi,t)
plot(t,24*h0s/pi,type="l")
```

```{r}
day<-180
phi=(pi/180)*50
S0=1368
t=seq(1,366,length.out=365*288)
daybegin<-day*288
dayend<-(day+1)*288
Q<-solarFlux(S0,phi,t)
plot(t[daybegin:dayend],Q[daybegin:dayend],type="l")
```

